export const USUARIO_REGISTRO_EXITOSO = 'USUARIO_REGISTRO_EXITOSO'
export const USUARIO_LOGIN_EXITOSO = 'USUARIO_LOGIN_EXITOSO'

export const LISTAR_USUARIOS = 'LISTAR_USUARIOS'

export const ADMIN_AGREGA_USUARIO = 'ADMIN_AGREGA_USUARIO'
export const ADMIN_ELIMINA_USUARIO = 'ADMIN_ELIMINA_USUARIO'
export const ADMIN_MODIFICA_USUARIO = 'ADMIN_MODIFICA_USUARIO'
export const ADMIN_CONSULTA_USUARIO = 'ADMIN_CONSULTA_USUARIO'

export const LISTAR_COMENTARIOS = 'LISTAR_COMENTARIOS'

export const ADMIN_AGREGA_COMENTARIO = 'ADMIN_AGREGA_COMENTARIO'
export const ADMIN_ELIMINA_COMENTARIO = 'ADMIN_ELIMINA_COMENTARIO'
export const ADMIN_MODIFICA_COMENTARIO = 'ADMIN_MODIFICA_COMENTARIO'
export const ADMIN_CONSULTA_COMENTARIO = 'ADMIN_CONSULTA_COMENTARIO'

export const LISTAR_CONTACTOS = 'LISTAR_CONTACTOS'

export const ADMIN_AGREGA_CONTACTO = 'ADMIN_AGREGA_CONTACTO'
export const ADMIN_ELIMINA_CONTACTO = 'ADMIN_ELIMINA_CONTACTO'
export const ADMIN_MODIFICA_CONTACTO = 'ADMIN_MODIFICA_CONTACTO'
export const ADMIN_CONSULTA_CONTACTO = 'ADMIN_CONSULTA_CONTACTO'

export const LISTAR_GALERIA = 'LISTAR_GALERIA'

export const ADMIN_AGREGA_GALERIA = 'ADMIN_AGREGA_GALERIA'
export const ADMIN_ELIMINA_GALERIA = 'ADMIN_ELIMINA_GALERIA'
export const ADMIN_MODIFICA_GALERIA = 'ADMIN_MODIFICA_GALERIA'
export const ADMIN_CONSULTA_GALERIA = 'ADMIN_CONSULTA_GALERIA'

export const LISTAR_POLITICAS = 'LISTAR_POLITICAS'

export const ADMIN_AGREGA_POLITICA = 'ADMIN_AGREGA_POLITICA'
export const ADMIN_ELIMINA_POLITICA = 'ADMIN_ELIMINA_POLITICA'
export const ADMIN_MODIFICA_POLITICA = 'ADMIN_MODIFICA_POLITICA'
export const ADMIN_CONSULTA_POLITICA = 'ADMIN_CONSULTA_POLITICA'

export const LISTAR_PRODUCTOS = 'LISTAR_PRODUCTOS'

export const ADMIN_AGREGA_PRODUCTO = 'ADMIN_AGREGA_PRODUCTO'
export const ADMIN_ELIMINA_PRODUCTO = 'ADMIN_ELIMINA_PRODUCTO'
export const ADMIN_MODIFICA_PRODUCTO = 'ADMIN_MODIFICA_PRODUCTO'
export const ADMIN_CONSULTA_PRODUCTO = 'ADMIN_CONSULTA_PRODUCTO'
export const ADMIN_ACTUALIZA_STOCK_PRODUCTO = 'ADMIN_ACTUALIZA_STOCK_PRODUCTO'

export const CERRAR_SESION = 'CERRAR_SESION'